module Levels exposing (level_01_str, level_error_str, level_list_str)

level_01_str =
        "..XXX........"
    ++  "..XoX........"
    ++  "..XbXXXX....."
    ++  "XXX pboX....."
    ++  "Xob  XXX....."
    ++  "XXXXbX......."
    ++  "...XoX......."
    ++  "...XXX......."

level_list_str =
    [ level_01_str
    
    ,       "XXXXX........"
        ++  "Xp  X........"
        ++  "X bbX.XXX...."
        ++  "X b X.XoX...."
        ++  "XXX XXXoX...."
        ++  ".XX    oX...."
        ++  ".X   X  X...."
        ++  ".X   XXXX...."
        ++  ".XXXXX......."

    ,       ".XXXXXXX....."
        ++  ".X  p  XXX..."
        ++  "XXbXXX   X..."
        ++  "X   b  b X..."
        ++  "X ooX b XX..."
        ++  "XXooX   X...."
        ++  ".XXXXXXXX...."

    ,       ".XXXX........"
        ++  "XX  X........"
        ++  "Xpb X........"
        ++  "XXb XX......."
        ++  "XX b X......."
        ++  "Xob  X......."
        ++  "XooKoX......."
        ++  "XXXXXX......."

    ,       ".XXXXX......."
        ++  ".Xp XXX......"
        ++  ".X b  X......"
        ++  "XXX X XX....."
        ++  "XoX X  X....."
        ++  "Xob  X X....."
        ++  "Xo   b X....."
        ++  "XXXXXXXX....."
    
    ,       "...XXXXXXX..."
        ++  "XXXX     X..."
        ++  "X   oXXX X..."
        ++  "X X X    XX.."
        ++  "X X B BXo X.."
        ++  "X X  K  X X.."
        ++  "X oXB B X X.."
        ++  "XX    X X XXX"
        ++  ".X XXXo    PX"
        ++  ".X     XX   X"
        ++  ".XXXXXXXXXXXX"

    ,       "...XXXXXXX..."
        ++  "..XX  X PX..."
        ++  "..X   X  X..."
        ++  "..XB B B X..."
        ++  "..X BXX  X..."
        ++  "XXX B X XX..."
        ++  "XOOOOO  X...."
        ++  "XXXXXXXXX...."

    ,       "...XXXXXX...."
        ++  ".XXX    X...."
        ++  "XXO BXX XX..."
        ++  "XOOB B  PX..."
        ++  "XOO B B XX..."
        ++  "XXXXXX  X...."
        ++  ".....XXXX...."

    ,       ".XXXXXXXXX..."
        ++  ".X  XX   X..."
        ++  ".X   B   X..."
        ++  ".XB XXX BX..."
        ++  ".X XOOOX X..."
        ++  "XX XOOOX Xx.."
        ++  "X B  B  B X.."
        ++  "X     X P X.."
        ++  "XXXXXXXXXXX.."

    ,      "..XXXXXX....."
        ++ "..X    X....."
        ++ "XXXBBB X....."
        ++ "XP BOO X....."
        ++ "X BOOOXX....."
        ++ "XXXX  X......"
        ++ "...XXXX......"

    ,       ".XXXX..XXXXX."
        ++ "XX  X..X   X."
        ++ "X B XXXXB  X."
        ++ "X  BOOOO B X."
        ++ "XX    X P XX."
        ++ ".XXXXXXXXXX.."

    ,       "..XXXXX......"
        ++  "XXX  PX......"
        ++  "X  Bo XX....."
        ++  "X  oBo X....."
        ++  "XXX KB X....."
        ++  "..X   XX....."
        ++  "..XXXXX......"
    
    ,       "..XXXX......."
        ++  "..XooX......."
        ++  ".XX oXX......"
        ++  ".X  boX......"
        ++  "XX b  XX....."
        ++  "X  Xbb X....."
        ++  "X  p   X....."
        ++  "XXXXXXXX....."

    ,       "XXXXXXXX....."
        ++  "X  X   X....."
        ++  "X boob X....."
        ++  "Xpbok XX....."
        ++  "X boob X....."
        ++  "X  X   X....."
        ++  "XXXXXXXX....."
        ++  "............."

    ,       ".XXXXXX......"
        ++  "XX    XX....."
        ++  "X b bb X....."
        ++  "XooooooX....."
        ++  "X bb b X....."
        ++  "XXX pXXX....."
        ++  "..XXXX......."
        ++  "............."

    ]

level_error_str =
        "...XXXXXXXXXX"
    ++  "...X   p    X"
    ++  "...XXXXXXXXXX"

